name: Java CI

on:
  push:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "Inner parameter for Allure TestOps"
        required: false
      ALLURE_USERNAME:
        description: "Inner parameter for Allure TestOps"
        required: false

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN_FOR_SELFHOSTED }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_ENDPOINT: http://localhost:8083
  ALLURE_PROJECT_ID: 2
  ALLURE_RESULTS: build/allure-results

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: http://localhost:8083
          allure-token: ${{ secrets.ALLURE_TOKEN_FOR_SELFHOSTED }}
          allure-project-id: 2
      - name: Run Tests
        working-directory: ${{ github.workspace }}
        run: |
          echo "Current dir: $(pwd)"
          .\gradlew.bat clean test
        env:
          ALLURE_RESULTS: ${{ env.ALLURE_RESULTS }}
