name: Java CI

on:
  push:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: "Inner parameter for Allure TestOps"
        required: false
      ALLURE_USERNAME:
        description: "Inner parameter for Allure TestOps"
        required: false

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_ENDPOINT: https://testing.qatools.cloud
  ALLURE_PROJECT_ID: 1790
  ALLURE_RESULTS: build/allure-results

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'gradle'
    - uses: allure-framework/setup-allurectl@v1
      with:
        allure-endpoint: https://testing.qatools.cloud
        allure-token: ${{ secrets.ALLURE_TOKEN }}
        allure-project-id: 1790
    - name: Run Tests
      run: allurectl watch -- ./gradlew clean test
      env:
        ALLURE_RESULTS: build/allure-results
